# Generated by Django 4.2.4 on 2023-10-27 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0003_feedback_freqaskedquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='mobile',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
