# Generated by Django 4.2.4 on 2023-10-27 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0004_feedback_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='designation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='image',
            field=models.ImageField(null=True, upload_to='feedbacks/'),
        ),
    ]
