# Generated by Django 4.2.4 on 2023-10-27 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0005_feedback_designation_feedback_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='email',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='mobile',
        ),
    ]
