# Generated by Django 4.2.4 on 2023-10-28 19:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0007_alter_feedback_designation_alter_feedback_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='library_documents/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Library Document',
                'verbose_name_plural': 'Library Documents',
            },
        ),
    ]
