# Generated by Django 4.2.4 on 2023-10-31 19:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0008_librarydocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revalidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200, unique=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('done', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Revalidate',
                'verbose_name_plural': 'Revalidate',
            },
        ),
    ]
