# Generated by Django 4.2.4 on 2023-11-07 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0009_revalidate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewArrivals',
        ),
    ]
