# Generated by Django 4.2.4 on 2023-11-09 03:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0010_delete_newarrivals'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('revalidate_url', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Website Text',
                'verbose_name_plural': 'Website Texts',
            },
        ),
    ]
