# Generated by Django 4.2.4 on 2023-11-09 10:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0011_websitetext'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitetext',
            name='static_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='websitetext',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
