# Generated by Django 4.2.4 on 2023-11-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0012_websitetext_static_id_alter_websitetext_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitetext',
            name='revalidate_url',
            field=models.CharField(max_length=200),
        ),
    ]
