# Generated by Django 5.0.1 on 2024-04-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0015_dataexcel'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataexcel',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=100, null=True),
        ),
    ]
