# Generated by Django 4.2.4 on 2024-04-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0016_dataexcel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataexcel',
            name='purpose',
            field=models.CharField(blank=True, choices=[('EBooks', 'EBooks'), ('EJournals', 'EJournals'), ('Faculty', 'Faculty'), ('Student', 'Student')], max_length=100, null=True),
        ),
    ]
