# Generated by Django 4.2.4 on 2023-10-17 10:28

from django.db import migrations, models
import django.db.models.deletion
import external_links.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkClass',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Heading')),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LinkSite',
            fields=[
                ('site_name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Name of the site')),
                ('image', models.ImageField(max_length=200, upload_to=external_links.models.image_path_link_site)),
                ('link_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='external_links.linkclass')),
            ],
        ),
        migrations.CreateModel(
            name='LinkURL',
            fields=[
                ('url', models.URLField(primary_key=True, serialize=False)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='external_links.linksite')),
            ],
        ),
    ]
