# Generated by Django 4.2.4 on 2023-10-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_links', '0002_alter_linkclass_options_alter_linksite_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenETDs',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Name of the site')),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'OpenETDs',
                'verbose_name_plural': 'OpenETDs',
            },
        ),
    ]
