# Generated by Django 4.2.4 on 2023-10-22 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_links', '0003_openetds'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OpenETDs',
        ),
        migrations.RemoveField(
            model_name='linksite',
            name='link_class',
        ),
        migrations.AddField(
            model_name='linksite',
            name='link_type',
            field=models.CharField(choices=[('Research Assistance', 'Research Assistance'), ('Open ETDs', 'Open ETDs')], default='Research Assistance', max_length=100),
        ),
        migrations.DeleteModel(
            name='LinkClass',
        ),
    ]
