# Generated by Django 4.2.4 on 2023-10-25 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_links', '0004_delete_openetds_remove_linksite_link_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InflibnetLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'INFLIBNET Link',
                'verbose_name_plural': 'INFLIBNET Links',
            },
        ),
    ]
