# Generated by Django 4.2.4 on 2023-10-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_links', '0005_inflibnetlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='linksite',
            name='file',
            field=models.FileField(null=True, upload_to='link_sites/'),
        ),
        migrations.AlterField(
            model_name='linksite',
            name='link_type',
            field=models.CharField(choices=[('Research Assistance', 'Research Assistance'), ('Open ETDs', 'Open ETDs'), ('Download Form', 'Download Form')], default='Research Assistance', max_length=100),
        ),
        migrations.AlterField(
            model_name='linksite',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
