# Generated by Django 4.2.4 on 2023-10-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_links', '0006_linksite_file_alter_linksite_link_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linksite',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='link_sites/'),
        ),
        migrations.AlterField(
            model_name='linksite',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
