# Generated by Django 4.2.4 on 2023-11-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_links', '0008_linksite_site_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linksite',
            name='link_type',
            field=models.CharField(choices=[('Research Assistance', 'Research Assistance'), ('Open ETDs', 'Open ETDs'), ('Download Form', 'Download Form'), ('Inflibnet', 'Inflibnet')], default='Research Assistance', max_length=100),
        ),
    ]
