# Generated by Django 4.2.4 on 2023-10-28 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleBookRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('extra_data', models.JSONField(default=dict)),
                ('type_doc', models.CharField(choices=[('Article', 'Article'), ('Book', 'Book')], default='Article', max_length=200)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_requests', to='users.userprofile')),
            ],
            options={
                'verbose_name': 'Article Request',
                'verbose_name_plural': 'Article Requests',
            },
        ),
    ]
