# Generated by Django 4.2.4 on 2023-10-31 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_item_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('Student', 'Student'), ('Faculty', 'Faculty'), ('Staff', 'Staff'), ('Research Scholar', 'Research Scholar'), ('Alumni', 'Alumni'), ('Other', 'Other')], default='Student', max_length=20),
        ),
    ]
