# Generated by Django 4.2.4 on 2024-03-18 15:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_claim_status_freebook_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlebookrequest',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
