# Generated by Django 5.0.1 on 2024-04-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_articlebookrequest_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('Student', 'Student'), ('Faculty', 'Faculty'), ('Staff', 'Staff'), ('Research Scholar', 'Research Scholar'), ('Alumni', 'Alumni'), ('Other', 'Other'), ('Admin', 'Admin')], default='Student', max_length=20),
        ),
    ]
