# Generated by Django 4.2.4 on 2023-10-31 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='exam',
        ),
        migrations.AddField(
            model_name='paper',
            name='hide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paper',
            name='semester',
            field=models.CharField(blank=True, choices=[('First', 'First'), ('Second', 'Second')], max_length=60),
        ),
    ]
