# Generated by Django 4.2.4 on 2023-11-07 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_remove_paper_exam_paper_hide_paper_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=60)),
                ('extra_data', models.JSONField(blank=True, default=dict, null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='textbooks', to='papers.course')),
            ],
            options={
                'verbose_name': 'TextBook',
                'verbose_name_plural': 'TextBooks',
            },
        ),
    ]
