# Generated by Django 4.2.4 on 2023-11-07 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_textbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbook',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
