# Generated by Django 4.2.4 on 2023-11-07 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0004_textbook_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbook',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
