# Generated by Django 4.2.4 on 2023-11-15 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0006_bitscampus_course_campus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='campus',
        ),
    ]
