# Generated by Django 4.2.4 on 2023-11-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0008_alter_paper_campus_alter_paper_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='exam',
            field=models.CharField(blank=True, choices=[('Comprehensive', 'Comprehensive'), ('Mid Semester', 'Mid Semester')], max_length=60),
        ),
    ]
