# Generated by Django 5.0.1 on 2024-02-26 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0009_paper_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbook',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
