# Generated by Django 4.2.4 on 2023-10-21 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('name', models.CharField(blank=True, max_length=60, primary_key=True, serialize=False)),
                ('is_main', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Campus',
                'verbose_name_plural': 'Campuses',
            },
        ),
        migrations.CreateModel(
            name='Database',
            fields=[
                ('name', models.CharField(blank=True, max_length=60, primary_key=True, serialize=False)),
                ('link', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='databases', to='databases.campus')),
            ],
            options={
                'verbose_name': 'Database',
                'verbose_name_plural': 'Databases',
            },
        ),
    ]
