# Generated by Django 4.2.4 on 2023-10-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
