# Generated by Django 4.2.4 on 2023-10-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0002_alter_database_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='is_trial',
            field=models.BooleanField(default=False),
        ),
    ]
