# Generated by Django 4.2.4 on 2023-10-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0003_database_is_trial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='campus',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='campus_images'),
        ),
    ]
