# Generated by Django 4.2.4 on 2023-10-23 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0004_campus_extra_data_campus_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='campus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='databases', to='databases.campus'),
        ),
    ]
