# Generated by Django 4.2.4 on 2023-10-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0006_publisher_subject_ebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='author',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='name',
            field=models.CharField(blank=True, max_length=160, primary_key=True, serialize=False),
        ),
    ]
