# Generated by Django 4.2.4 on 2023-10-24 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0007_alter_ebook_author_alter_ebook_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EBook',
        ),
    ]
