# Generated by Django 4.2.4 on 2023-10-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0010_alter_ebook_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='name',
            field=models.TextField(blank=True),
        ),
    ]
