# Generated by Django 4.2.4 on 2023-10-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0011_alter_ebook_name'),
    ]


    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(blank=True, max_length=200, primary_key=True, serialize=False),
        ),
    ]
