# Generated by Django 4.2.4 on 2023-10-24 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0013_alter_publisher_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EBook',
        ),
    ]
