# Generated by Django 4.2.4 on 2023-10-27 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0018_ejournal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ELearning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('link', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'E-Learning',
                'verbose_name_plural': 'E-Learnings',
            },
        ),
        migrations.CreateModel(
            name='OpenAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('link', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Open Access',
                'verbose_name_plural': 'Open Access',
            },
        ),
        migrations.RemoveField(
            model_name='ejournal',
            name='description',
        ),
    ]
