# Generated by Django 4.2.4 on 2023-10-27 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0019_elearning_openaccess_remove_ejournal_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebook',
            name='description',
        ),
    ]
