# Generated by Django 4.2.4 on 2023-10-29 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0024_rename_link_elearning_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='campus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to='databases.campus'),
        ),
    ]
