# Generated by Django 4.2.4 on 2023-10-30 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0025_platform_campus'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='database',
            name='name',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
