# Generated by Django 4.2.4 on 2023-11-07 17:52

import databases.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0027_make_primary_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewArrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('file', models.FileField(blank=True, null=True, upload_to=databases.models.new_arrival_path)),
            ],
            options={
                'verbose_name': 'New Arrival',
                'verbose_name_plural': 'New Arrivals',
            },
        ),
    ]
