# Generated by Django 4.2.4 on 2023-11-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0029_database_user_guide'),
    ]

    operations = [
        migrations.RenameField(
            model_name='database',
            old_name='user_guide',
            new_name='user_guide_file',
        ),
        migrations.AddField(
            model_name='database',
            name='user_guide_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
