# Generated by Django 4.2.4 on 2023-11-18 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0030_rename_user_guide_database_user_guide_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='user_guide_file',
            field=models.FileField(blank=True, null=True, upload_to='database_user_guides'),
        ),
        migrations.AddField(
            model_name='platform',
            name='user_guide_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
