# Generated by Django 4.2.4 on 2023-11-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0031_platform_user_guide_file_platform_user_guide_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='newarrival',
            name='position',
            field=models.IntegerField(default=1),
        ),
    ]
