# Generated by Django 4.2.4 on 2023-11-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0033_donatedbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donatedbook',
            name='donor',
            field=models.CharField(max_length=200),
        ),
    ]
