# Generated by Django 4.2.4 on 2023-11-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0034_alter_donatedbook_donor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donatedbook',
            options={'verbose_name': 'Donated Book or BITSian Authored Book', 'verbose_name_plural': 'Donated Books BITSian Authored Books'},
        ),
        migrations.AddField(
            model_name='donatedbook',
            name='book_type',
            field=models.CharField(blank=True, choices=[('Donated Book', 'Donated Book'), ('BITSian Authored Book', 'BITSian Authored Book')], max_length=60),
        ),
        migrations.AlterField(
            model_name='donatedbook',
            name='donor',
            field=models.CharField(blank=True, max_length=200, verbose_name='Donor or BITSian Author'),
        ),
    ]
