# Generated by Django 4.2.4 on 2023-11-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0035_alter_donatedbook_options_donatedbook_book_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donatedbook',
            name='book_type',
            field=models.CharField(blank=True, choices=[('DonatedBook', 'DonatedBook'), ('BITSianAuthoredBook', 'BITSianAuthoredBook')], max_length=60),
        ),
    ]
