# Generated by Django 4.2.4 on 2023-11-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0036_alter_donatedbook_book_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donatedbook',
            name='book_type',
            field=models.CharField(choices=[('DonatedBook', 'DonatedBook'), ('BITSianAuthoredBook', 'BITSianAuthoredBook')], default='DonatedBook', max_length=60),
        ),
    ]
