# Generated by Django 4.2.4 on 2024-01-31 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0038_alter_donatedbook_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donatedbook',
            name='book_type',
            field=models.CharField(choices=[('DonatedBook', 'DonatedBook'), ('BITSianAuthoredBook', 'BITSianAuthoredBook'), ('NewArrival', 'NewArrival')], default='DonatedBook', max_length=60),
        ),
    ]
