# Generated by Django 5.0.1 on 2024-02-26 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0039_alter_donatedbook_book_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publisher',
            options={'ordering': ['name'], 'verbose_name': 'Publisher', 'verbose_name_plural': 'Publishers'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name'], 'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
    ]
