# Generated by Django 4.0.10 on 2024-08-31 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0040_alter_publisher_options_alter_subject_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.TextField(blank=True)),
                ('title', models.TextField(blank=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('source_title', models.TextField(blank=True)),
                ('volume', models.TextField(blank=True)),
                ('issue', models.TextField(blank=True)),
                ('doi', models.TextField(blank=True)),
                ('publisher', models.TextField(blank=True)),
                ('issn', models.TextField(blank=True)),
                ('publication_type', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
            },
        ),
    ]
