# Generated by Django 4.0.10 on 2024-09-12 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0042_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
