# Generated by Django 4.2.4 on 2023-09-07 05:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60)),
                ('capacity', models.IntegerField(null=True)),
                ('slots', models.DurationField(default=datetime.timedelta(seconds=3600))),
                ('num_slots', models.PositiveIntegerField(default=9)),
            ],
        ),
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60)),
                ('rooms', models.ManyToManyField(related_name='facilities', to='booking.room')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=40)),
                ('condition', models.TextField(blank=True)),
                ('slot', models.IntegerField(default=1)),
                ('booker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_rooms', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_rooms', to='booking.room')),
            ],
        ),
    ]
