# Generated by Django 4.2.4 on 2023-10-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_facility_roomslot_remove_booking_room_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name': 'Facility', 'verbose_name_plural': 'Facilities'},
        ),
        migrations.AlterModelOptions(
            name='roomslot',
            options={},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='requirements',
        ),
        migrations.AddField(
            model_name='booking',
            name='requirements',
            field=models.JSONField(default=list),
        ),
    ]
