# Generated by Django 4.2.4 on 2023-10-25 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_room_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='requirements',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
