# Generated by Django 4.2.4 on 2023-10-25 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_room_description_roomrule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomRule',
        ),
    ]
