# Generated by Django 4.2.4 on 2023-10-25 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_delete_roomrule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomslot',
            options={'verbose_name': 'Room Slot', 'verbose_name_plural': 'Room Slots'},
        ),
        migrations.AlterUniqueTogether(
            name='roomslot',
            unique_together={('room', 'slot')},
        ),
    ]
