# Generated by Django 4.2.4 on 2023-11-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_alter_roomslot_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
