# Generated by Django 4.2.4 on 2023-11-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_room_extra_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='extra_data',
        ),
        migrations.AddField(
            model_name='facility',
            name='cost_per_minute',
            field=models.IntegerField(default=0),
        ),
    ]
