# Generated by Django 4.2.4 on 2023-11-18 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_remove_room_extra_data_facility_cost_per_minute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='capacity',
        ),
        migrations.AddField(
            model_name='room',
            name='max_capacity',
            field=models.IntegerField(null=True, verbose_name='Max Room Capacity'),
        ),
        migrations.AddField(
            model_name='room',
            name='min_capacity',
            field=models.IntegerField(null=True, verbose_name='Min Room Capacity'),
        ),
    ]
