# Generated by Django 4.2.4 on 2023-11-19 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_booking_booking_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facility',
            old_name='cost_per_minute',
            new_name='cost',
        ),
    ]
