# Generated by Django 4.2.4 on 2023-11-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_booking_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Is Room Closed for Booking?'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_closing_reason',
            field=models.TextField(blank=True),
        ),
    ]
