# Generated by Django 4.2.4 on 2023-08-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_rename_tabularrules_tabularrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=50)),
                ('link', models.TextField(blank=True)),
                ('hidden', models.BooleanField(default=False)),
            ],
        ),
    ]
