# Generated by Django 4.2.4 on 2023-10-01 07:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_librarybrochure'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('imgae', models.ImageField(max_length=200, upload_to='timings')),
                ('is_set', models.BooleanField(default=True)),
            ],
        ),
    ]
