# Generated by Django 4.2.4 on 2023-10-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_librarytiming'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryteammember',
            name='is_librarian',
            field=models.BooleanField(default=False),
        ),
    ]
