# Generated by Django 4.2.4 on 2023-10-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_libraryteammember_is_librarian'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryteammember',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
