# Generated by Django 4.2.4 on 2023-10-24 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0010_event_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='librarycommitteemember',
            old_name='mobile_number',
            new_name='phone_number',
        ),
    ]
