# Generated by Django 4.2.4 on 2023-10-25 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0011_rename_mobile_number_librarycommitteemember_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
    ]
