# Generated by Django 4.2.4 on 2023-10-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0012_alter_news_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarycommitteemember',
            name='department',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='libraryteammember',
            name='designation',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
