# Generated by Django 4.2.4 on 2023-11-04 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0013_alter_librarycommitteemember_department_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
