# Generated by Django 4.2.4 on 2023-11-08 04:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0014_delete_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookMarquee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=20)),
                ('is_set', models.BooleanField(default=True)),
                ('uploaded_on', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Book Marquee',
                'verbose_name_plural': 'Book Marquees',
            },
        ),
    ]
