# Generated by Django 4.2.4 on 2023-11-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0016_alter_libraryteam_is_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarycommitteemember',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Images/LibraryCommitteeMembers'),
        ),
    ]
