# Generated by Django 4.2.4 on 2023-11-18 05:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0017_librarycommitteemember_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryWebsiteUserGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.FileField(max_length=200, upload_to='brochure')),
                ('is_set', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
