# Generated by Django 4.2.4 on 2023-11-19 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0019_alter_librarywebsiteuserguide_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='url',
        ),
        migrations.AddField(
            model_name='event',
            name='url_file',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='events'),
        ),
        migrations.AddField(
            model_name='event',
            name='url_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='url_file',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='news'),
        ),
        migrations.AddField(
            model_name='news',
            name='url_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
