# Generated by Django 4.2.4 on 2023-11-19 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0020_remove_news_url_event_url_file_event_url_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='source',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='news',
            name='url_file',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='news', verbose_name='PDF/Image of News'),
        ),
        migrations.AlterField(
            model_name='news',
            name='url_link',
            field=models.URLField(blank=True, null=True, verbose_name='Link to News'),
        ),
    ]
