# Generated by Django 4.2.4 on 2023-11-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0023_librarycalendar_delete_librarytiming'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('is_open', models.BooleanField(default=True)),
                ('is_holiday', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Library Timing',
                'verbose_name_plural': 'Library Timings',
            },
        ),
    ]
