# Generated by Django 4.2.4 on 2023-11-22 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0025_librarytiming_holiday_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librarytiming',
            name='is_open',
        ),
    ]
