# Generated by Django 4.2.4 on 2023-11-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0030_remove_librarywebsiteuserguide_is_set_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarywebsiteuserguide',
            name='file',
            field=models.FileField(blank=True, max_length=200, upload_to='user_guide'),
        ),
    ]
