# Generated by Django 4.2.4 on 2023-11-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0031_alter_librarywebsiteuserguide_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarycommitteemember',
            name='designation',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
