# Generated by Django 4.2.4 on 2024-03-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0032_librarycommitteemember_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librarycollection',
            name='is_set',
        ),
        migrations.AddField(
            model_name='bookmarquee',
            name='campus',
            field=models.CharField(choices=[('Pilani', 'Pilani'), ('Goa', 'Goa'), ('Hyderabad', 'Hyderabad'), ('Dubai', 'Dubai'), ('Mumbai', 'Mumbai')], default='Pilani', max_length=20),
        ),
        migrations.AddField(
            model_name='librarycollection',
            name='campus',
            field=models.CharField(choices=[('Pilani', 'Pilani'), ('Goa', 'Goa'), ('Hyderabad', 'Hyderabad'), ('Dubai', 'Dubai'), ('Mumbai', 'Mumbai')], default='Pilani', max_length=20),
        ),
    ]
